### ISSUE TITLE
Test failures on dual stack ipv4/ipv6 with EV installed

### ISSUE THREAD

**Issue by mikemagowan** [jhthorsen/mojo-redis2#12]
Hi,

Had tests fail when using EV and a specific configuration of /etc/hosts.  The failures look like:

http://pastebin.com/8RtGpFuH

If EV is not installed - all tests pass.  In addition /etc/hosts is configured as the following:

    127.0.0.1       localhost
    ::1            localhost

If I comment out the ::1 localhost entry then everything works ok and the tests pass.  Looks like the ipv4/ipv6 stack used by the tests / redis is different when EV is involved?

This is on 64bit Linux with Perl 5.20.2 and EV (v4.21)

**Comment by jhthorsen** [comment]
Thank you! I've been struggling with understanding why these tests fail:

http://cpantesters.org/cpan/report/71fe8bee-2b21-11e5-afae-fde0e0bfc7aa
http://cpantesters.org/cpan/report/7325f7dc-2b21-11e5-afae-fde0e0bfc7aa
http://cpantesters.org/cpan/report/743dbeb6-2b21-11e5-afae-fde0e0bfc7aa
http://cpantesters.org/cpan/report/75505a5c-2b21-11e5-afae-fde0e0bfc7aa

But now I might be able to reproduce it after your input. I will try your setup later today.

**Comment by jhthorsen** [comment]
I think this fixes it. I'm not sure if I like the solution though, since it won't work if you only have IPv6. I think I will worry about that in the future. Please let me know if you know of better solution.

I considered removing "bind" completely, but then the test server would listen to all interfaces, which I don't think is a good idea.

3ed5d3c

**Comment by mikemagowan** [comment]
Yep - confirmed that this fixes it.  Think it the best solution for now and it follows the same principle as redis in that the default in redis.conf is to bind to 127.0.0.1 (or specific interface IP) rather than a hostname.

**Comment by jhthorsen** [comment]
Thanks :+1:
