### ISSUE TITLE
Support connecting to redis using a UNIX socket

### ISSUE THREAD

**Issue by dani** [jhthorsen/mojo-redis2#14]
Looks like it's not possible for now to connect to redis over a UNIX socket, only TCP is possible. Would be cool to have UNIX socket supported

**Comment by jhthorsen** [comment]
Could you provide a better reason than "cool" ?

**Comment by dani** [comment]
Of course. I always prefer UNIX socket over inet socket when possible because it can provide a better security, as we can restrict permission on it.

**Comment by jhthorsen** [comment]
Do you have people you don't trust locally on the server?

**Comment by jhthorsen** [comment]
Anyway... I don't think this is going to happen because of https://github.com/kraih/mojo/issues/883

I think if you have some killer argument, you should rather comment on that issue.

I consider binding to 127.0.0.1 just as secure as sockets. I understand that in _theory_ it's not, but that's probably because I don't have users I don't trust that has login to the server. Please give a practical scenario where this is not true. It might help #833 above.

**Comment by mpapec** [comment]
Security is almost a non issue here, but it would be interesting to see tcp vs. unix socket client bencharks regerding op/s and latency.

Regards

**Comment by CodingMinds** [comment]
I've added my use case to https://github.com/kraih/mojo/issues/883

**Comment by Grinnz** [comment]
Support for http over unix sockets was added to Mojolicious in https://github.com/kraih/mojo/commit/8f6e21410f240b3a055d3c42a270382a7fc3a676 so this might be possible now.

**Comment by yuriy-zhilovets2** [comment]
_Redis2.pm:126_
```
+ my $conn_args = {};
+ if ($url->scheme eq "http+unix" || $url->scheme eq "redis+unix")
+ {
+  $conn_args->{path} => $url->path;
+  $url->query =~ /^db=(\d+)/;
+  $db = $1;
+ }
+ else
+ {
+  $conn_args->{address} = $url->host;
+  $conn_args->{port} = $url->port || DEFAULT_PORT;
+ }
$c->{id} = $self->_loop($c->{nb})->client(
-  {address => $url->host, port => $url->port || DEFAULT_PORT},
+ $conn_args,
```

**Usage:**

use Mojo::URL;
my $url = new Mojo::URL("redis+unix:///tmp/redis.sock?db=1"); # or just "redis+unix:///tmp/redis.sock

**Comment by jhthorsen** [comment]
I'm going to stop maintaining Mojo::Redis2 officially now, and focus on Mojo::Redis instead.

**Comment by jhthorsen** [comment]
Closing this, since I implemented it in Mojo::Redis.
