### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by biancalana** [jhthorsen/mojo-redis2#16]
I'm using some blocking calls inside eval, on error condition (ie: connection refused) the error that I get from $@ contain the entire command, args plus error...

```
[SETEX session:aaa6b981ba613e00b525f230d916afcaf777ba16eec30409734c71d72915e4aaa4669a610a9491405d08f120ca4acbc189ec7101ae2729412ab97e9b238d07db 7200 
?aaa6b981ba613e00b525f230d916afcaf777ba16eec30409734c71d72915e4aaa4669a610a9491405d08f120ca4acbc189ec7101ae2729412ab97e9b238d07dbkey    127.0.0.1ip
defaulttypeaaaaaabaaaa1212?ctime$BD621822-82A0-11E5-BB77-FE21DD7EB77Euser_id] Connection refused at /usr/local/lib/perl5/site_perl/Mojo/Redis2.pm line 556.
```

Do you suggest anything so I can get only the error msg ? ie: connection refused

I would like to avoid treat $@ on every cal...

**Comment by jhthorsen** [comment]
Not sure. The reason why the command is part of the error message is that in case of command failure, it will be impossible to know which command failed when receiving the error message. But on the other hand, I think this is only true for bulk operations...

Anyway - Why do you want to remove it?

**Comment by biancalana** [comment]
Im doing some operations (setnx in that case) inside a submodule,  for matter o sane/clear error logging I just need command and the error...

**Comment by jhthorsen** [comment]
But that's exactly what you get: the command and error.

**Comment by biancalana** [comment]
No, i'm getting command parameters also...

**Comment by jhthorsen** [comment]
Ah! So you'll be ok with "[SETEX] Connection refused" ?

**Comment by biancalana** [comment]
yes

**Comment by jhthorsen** [comment]
I'm closing this issue, since it's really old.

Would you like to take over maintenance? I would give you commit bit to this repo and you could push new releases to CPAN.
