### ISSUE TITLE
Read/write timeout

### ISSUE THREAD

**Issue by marcantonio** [jhthorsen/mojo-redis2#24]
Is it possible to specify read/write/connect timeouts?

**Comment by jhthorsen** [comment]
No, why do you need that?

We could add "connect timeout" here: https://github.com/jhthorsen/mojo-redis2/blob/master/lib/Mojo/Redis2.pm#L123. Not sure if it's best to have it as part of the $url or something else.

**Comment by jhthorsen** [comment]
Closing this, since it there seems to be little interest for this.
