### ISSUE TITLE
How to send raw (byte) data with Mojo::Redis2?

### ISSUE THREAD

**Issue by DRVTiny** [jhthorsen/mojo-redis2#36]
Hello!

Thank you very much for your great work!

I've written Redis::BCStation package, which uses Mojo::Redis2 as a backend.
I have some problems when publishing "big" blob data: i have no errors/exceptions returned from Mojo::Redis2, but the data not published too. The data is 11M CBOR'ed perl datastructure which contains many russian letters. It's very strange, but small blobs with cyrillic symbols goes well through pub/sub: message arrives to subscribed handlers, its CRC is correct.

I was trying to set Mojo::Redis2 "bytes" encoding such as US-ASCII - but no changes at all.
If i replace encode_cbor for encode_json - my blob is growth for ~35% in size, but it is published succesfully. 

How to avoid this problem? I use CBOR because of its compactness (and excellent coding speed too), so i cant simply base64-covering my data before sending to Redis.

Thank you!

**Comment by mikemagowan** [comment]
It should work if you don't use Protocol::Redis::XS

There's a bug in that module that doesn't like \x00 so any instances of that in your blob will cause a failure.

**Comment by Grinnz** [comment]
That would explain some behavior I've seen; it would be great if someone familiar with the issue could file a bug against that module!

**Comment by Grinnz** [comment]
I see you already have a PR, so linking it to here: https://github.com/dgl/protocol-redis-xs/pull/2

**Comment by Grinnz** [comment]
By the way, the correct way to send byte data is to set the encoding attribute to `undef`.

**Comment by DRVTiny** [comment]
I am using Protocol::Redis::XS, it is more robust than Protocol::Redis...
So i can avoid bug in this module using encoding(undef), right?

**Comment by mikemagowan** [comment]
No it can't be avoided by setting encoding(undef).

The underlying bug in Protocol::Redis::XS will cause failure when any null character is passed through.

**Comment by DRVTiny** [comment]
Its a pitty :(

But any way - thank you very much! I'll reopen issue for Protocol::Redis::XS.

**Comment by DRVTiny** [comment]
I confirm that with protocol_class('Protocol::Redis') my code works as expected, but with Protocol::Redis::XS - publish method dies silently/ Error may be catched with try {} catch {} but it contains no $_ in error description ($_==undef): its's very like to bug in C-code of the Protocol::Redis::XS module.

**Comment by DRVTiny** [comment]
Maybe, you can make it possible to use http://zzzcpan.github.io/nginx-perl/Redis/Parser/XS.html instead of Protocol::Redis::XS?

**Comment by jhthorsen** [comment]
@DRVTiny: you can try that yourself:

```
use RedisDB::Parser::XS;
my $redis = Mojo::Redis2->new(protocol_class => "RedisDB::Parser::XS");
```

**Comment by DRVTiny** [comment]
This is incompatible with Protocol::Redis::XS
OK, maybe i'll try to write some "proxy package". Mojo::Redis2 is too slow to use it without any XS.
