### ISSUE TITLE
Will not resubscribe to messages on reconnect

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojo-redis2#4]
I think I need to add support for doing (P)SUBSCRIBE after connection is re-established.

Need to think this though before adding complexity.

1. $redis->subscribe("foo");
2. Connection breakes down
3. $redis reconnects automatically when a new GET,SET,... is issued
4. But there will be no new "message" events, since (P)SUBSCRIBE has not been sent over the wire.

**Comment by jhthorsen** [comment]
Closing this since there seems to be little interest in the subject.

**Comment by qknight** [comment]
i'm now using this code which makes a keep-alive request all `5 seconds` and if redis goes down and comes up again, i will see `$redis->on(connection ...` and that will re-subscribe the subscription:

```perl
$redis->on(connection => sub { my ($self, $info) = @_; 
  say "connection established";
  $redis->subscribe(['rt-ticket-activity'], sub { 
    my ($self, $err, $res) = @_; 
  });
});

Mojo::IOLoop->recurring(5 => sub {
  my $loop = shift;
  $redis->get("foo");
});
```

**Comment by jhthorsen** [comment]
@qknight: Do you have a test for this as well?

**Comment by qknight** [comment]
i don't have a test, but wouldn't that code about just work already?

**Comment by jhthorsen** [comment]
Well... That's the whole point of a test: I have no idea, but a test would tell me if it works at all.

Or wait: Did you put that comment as an example, or because you wanted me to put it in Mojo::Redis2?

**Comment by qknight** [comment]
the code i pasted here is actually used in this mojolicious code:
  https://github.com/nixcloud/rt-coreExtension-websocket

see
  https://github.com/nixcloud/rt-coreExtension-websocket/blob/master/rt-coreExtension-websocket.pl#L32

this is code we use in production and it works very well! i love your mojo-redis2 implementation, thanks for creating it!

anyway, i would like to provide a test for this code. can you advice me how to create one, i would like to learn that.
