### ISSUE TITLE
zrange doesn't return the same thing in list context as scalar context

### ISSUE THREAD

**Issue by denimboy** [jhthorsen/mojo-redis2#40]
Hi,

I have an application which uses redis sorted sets in the backend.  I am migrating the frontend to Mojo so I would like to use Mojo::Redis2 to access redis asynchronously.

I ran into an issue where calling zrange in list context returns different results than in scalar context.  In scalar context zrange returns a listref of results; [ 'foo', 'bar', baz'] but in list context the results are embedded in another listref; [ [ 'foo', 'bar', baz'] ]

I compared this against the Redis module from CPAN and it returns a listref (not listref of listref) every time.  I was able to reproduce this behavior with both zrange and zrevrange.  I am not sure about other sorted sets functionality.

Small test case illustrating the issue is included below.

Thanks,

D

````perl
#!perl                                                                                                                                                                            

use strict;
use warnings;

use Test::More;
use Redis;
use Mojo::Redis2;

my $r = Redis->new;
my $mr2 = Mojo::Redis2->new;

my $key = '_test:123';

for my $i (0..10) {
    $r->zadd($key, $i, "$key $i");
}

# redis                                                                                                                                                                       
my $redis_ref = $r->zrange($key, 0, 10);
my @redis_lis = $r->zrange($key, 0, 10);

# mojo::redis2                                                                                                                                                                
my $mr2_ref = $mr2->zrange($key, 0, 10);
my @mr2_lis = $mr2->zrange($key, 0, 10);

# ok
is_deeply(\@redis_lis, $redis_ref, "redis_lis same as redis_ref")
    || diag(explain($redis_ref, \@redis_lis));
is_deeply($mr2_ref, $redis_ref, "mr2_ref same as redis_ref")
    || diag(explain($redis_ref, $mr2_ref));

# not ok
is_deeply(\@mr2_lis, $mr2_ref, "mr2_lis same as mr2_ref")
    || diag(explain($mr2_ref, \@mr2_lis));

$r->del($key);
done_testing;
````

**Comment by Grinnz** [comment]
The return value is the same. It might be helpful to use more precise terminology. The methods return an array reference, which is a scalar value, regardless of context. When you store that array reference in an array, the array now contains an array reference. Your test is comparing a reference to that array (containing the array reference result) with the array reference result normally returned.

**Comment by Grinnz** [comment]
On the other hand, the Redis methods are context-sensitive, and return a list rather than an arrayref in list context, as documented. This can lead to [bad surprises](https://metacpan.org/pod/Perl::Critic::Policy::Freenode::Wantarray).

**Comment by Grinnz** [comment]
This should help show both how Redis is returning values as well as the danger of context sensitivity:

```
my %redis_hash = (range => $r->zrange($key, 0, 10));
my %mr2_hash = (range => $mr2->zrange($key, 0, 10));
is_deeply(\%redis_hash, \%mr2_hash, "redis_hash same as mr2_hash")
    || diag(explain(\%redis_hash, \%mr2_hash));
```

**Comment by denimboy** [comment]
['foo'] and [['foo']] are different.  I think Mojo::Redis2 should return the same thing as Redis module.

**Comment by Grinnz** [comment]
It's not returning [['foo']], you are storing the result in an array when it is a scalar. Mojo::Redis2 will not be changing its interface to a less secure one.
