### ISSUE TITLE
Custom redis call?

### ISSUE THREAD

**Issue by KnowZero** [jhthorsen/mojo-redis2#43]
Would it be possible to implement a function like:

`sub call {
    my ($self,$op)=(shift,shift);
    $self->_execute(basic => $op => @_);
}`
Or something similar.

As of Redis 4, there are now plugins like ReJSON and etc, so it would be nice to have an official API for sending custom calls.

**Comment by jhthorsen** [comment]
I'm going to stop maintaining Mojo::Redis2 officially now, and focus on Mojo::Redis instead.

I think it will be very easy to add what you ask for using the new module, by exposing https://github.com/jhthorsen/mojo-redis/blob/master/lib/Mojo/Redis/Database.pm#L47, but also adding a generic "call()" could be better?

**Comment by jhthorsen** [comment]
Closing this, since I implemented it in Mojo::Redis.
