### ISSUE TITLE
Is it possible to disconnect/reconnect in Mojo::Redis2?

### ISSUE THREAD

**Issue by DRVTiny** [jhthorsen/mojo-redis2#44]
Hello!

In some situations i want to be possible to disconnect from one Redis server and connect to another at runtime (to switch from slow connection to faster one or to switch from Redis server where  resources are limited to server without resource-related  limitations, etc.) It is very difficult to recreate Mojo::Redis2 instance because reference to this instance is used by many callbacks, which discourage decrementing reference count for this object/instance to 0.
Is it possible to reconnect without destroying Mojo::Redis2 instance? 
Thank you!

**Comment by jhthorsen** [comment]
I think I've implemented what you asked for in Mojo::Redis now.

1. If you change `$redis->url` then new database obects and connections will use the new url.
2. The existing connections will not be reused, unless the connection url matches the url on the redis object.
3. You can change the connection url and disconnect https://metacpan.org/pod/Mojo::Redis::Connection#url and https://metacpan.org/pod/Mojo::Redis::Connection#disconnect

**Comment by jhthorsen** [comment]
Closing this, since I implemented it in Mojo::Redis.
