### ISSUE TITLE
Unsubscribe support

### ISSUE THREAD

**Issue by CodingMinds** [jhthorsen/mojo-redis2#5]
It would be great if previously subscribed channels could be unsubscribed.
$redis->subscribe("foo" => sub {..})
.. fancy stuff ..
$redis->unsubscribe("foo" => sub {..})

**Comment by jhthorsen** [comment]
New version is soon available on CPAN.

Thanks for submitting an issue! :+1:

**Comment by CodingMinds** [comment]
Thanks for implementing this feature :smiley:

**Comment by jhthorsen** [comment]
You're welcome.
