### ISSUE TITLE
Docs don't mention return value of subscribe needs to be retained

### ISSUE THREAD

**Issue by akarelas** [jhthorsen/mojo-redis2#7]
The docs give this example:

```perl
$self->on(message => sub {
  my ($self, $message, $channel) = @_;
});
 
$self->subscribe("some:channel" => sub {
  my ($self, $err) = @_;
 
  return $self->publish("myapp:errors" => $err) if $err;
  return $self->incr("subscribed:to:some:channel");
});
```

However this example will not work, because the return value of $self->subscribe needs to be retained in a permanent variable, for the subscription to happen. So, change with:

```perl
our $subscription = $self->subscribe("some:channel" => sub {
```

**Comment by akarelas** [comment]
Bug report is wrong. See http://stackoverflow.com/questions/28639178/cant-get-mojoredis2-to-subscribe/28648094 for more.

**Comment by jhthorsen** [comment]
That is incorrect. The only thing you need to keep around is $self (aka $redis).

I need to see more code to tell you where you went wrong, but it looks like your ```our``` fix is not right (even though I'm not surprised if it seems to work). Is this in a Mojolicious web app or a standalone application? If it's an web app, then do something like this:

**Comment by akarelas** [comment]
It's a web app, but I can't see your code for some reason. All I can see in your comment is: "If it's an web app, then do something like this:" with nothing following that.

**Comment by jhthorsen** [comment]
Oh! Something was lost... Here you go:
```perl
websocket "/foo" => sub {
  my $c = shift;
  my $redis = Mojo::Redis2->new;

  # This is the important line:
  # Need to make sure $redis does not go out of scope (similar to our)
  $c->stash(redis => $redis);
 
  $c->on(message => sub {
    my ($c, $data) = @_;
    $redis->publish(whatever => $data);
  });
};
```
