### ISSUE TITLE
Need event when reconnection happens

### ISSUE THREAD

**Issue by akarelas** [jhthorsen/mojo-redis2#8]
I have a chat server that uses Redis for pubsub. The chat server needs to know when Redis has been disconnected and connected again, so that all clients will be notified about this event so they can fetch from the database the messages that were writted while Redis was down.

So we need a ```$redis->on('reconnect')``` event.

**Comment by jhthorsen** [comment]
I have no plan on implementing such a feature. I don't see why you can't use the exising ```connection``` event for this.

```
$self->on(error => sub {
  my ($self, $info) = @_;
  if ($info->{group} eq 'publish' and $reconnected++) {
    # do what you want
  }
});
```
