### ISSUE TITLE
Does Mojo::Redis2 re-connect if the Redis server is restarted?

### ISSUE THREAD

**Issue by akarelas** [jhthorsen/mojo-redis2#9]
Documentation mentions nothing about that. If yes, how often are retries made? See example options here: https://metacpan.org/pod/Redis

**Comment by jhthorsen** [comment]
It depends... It does not reconnect on an error, but it does reconnect if the socket is simply closed.

You can look for ```_error``` in the source code:
https://github.com/jhthorsen/mojo-redis2/blob/master/lib/Mojo/Redis2.pm#L461
https://github.com/jhthorsen/mojo-redis2/blob/master/lib/Mojo/Redis2.pm#L534

It will however reconnect on the next action. Let me try to give an example:

```perl
Mojo::IOloop->delay(
  sub {
    my ($delay) = @_;
    $redis->get("some:key" => $delay->begin);
  },
  sub {
    my ($delay, $err, $value) = @_;

    # this next get() will either connect again if $err is set
    # or use the existing connection, if still connected
    $redis->get("some:key" => $delay->begin);
  },
);
```
